try {
  flaky();
} catch exceptions.Exception1, exceptions.Exception2, exceptions.Exception3 as e {
  print(e);
} catch {
  print("I don't know what's going on");
}